/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bang;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author ctaylor
 */
public class BangSwingChar extends javax.swing.JFrame {

    /**
     * Creates new form BangSwingChar
     */
    public BangSwingChar() {
        initComponents();
        scaleIcons();
        skip();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        char_select = new javax.swing.JDialog();
        bart_img = new javax.swing.JLabel();
        black_img = new javax.swing.JLabel();
        calamity_img = new javax.swing.JLabel();
        gringo_img = new javax.swing.JLabel();
        paul_img = new javax.swing.JLabel();
        pedro_img = new javax.swing.JLabel();
        rose_img = new javax.swing.JLabel();
        sid_img = new javax.swing.JLabel();
        jesse_img = new javax.swing.JLabel();
        jour_img = new javax.swing.JLabel();
        kit_img = new javax.swing.JLabel();
        lucky_img = new javax.swing.JLabel();
        slab_img = new javax.swing.JLabel();
        suzy_img = new javax.swing.JLabel();
        vulture_img = new javax.swing.JLabel();
        willy_img = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bart = new javax.swing.JDialog();
        bart_desc = new javax.swing.JTextArea();
        bartb = new javax.swing.JButton();
        black = new javax.swing.JDialog();
        black_desc = new javax.swing.JTextArea();
        blackb = new javax.swing.JButton();
        calamity = new javax.swing.JDialog();
        calamity_desc = new javax.swing.JTextArea();
        calamityb = new javax.swing.JButton();
        gringo = new javax.swing.JDialog();
        gringo_desc = new javax.swing.JTextArea();
        gringob = new javax.swing.JButton();
        jesse = new javax.swing.JDialog();
        jesse_desc = new javax.swing.JTextArea();
        jesseb = new javax.swing.JButton();
        jour = new javax.swing.JDialog();
        jour_desc = new javax.swing.JTextArea();
        jourb = new javax.swing.JButton();
        kit = new javax.swing.JDialog();
        kit_desc = new javax.swing.JTextArea();
        kitb = new javax.swing.JButton();
        lucky = new javax.swing.JDialog();
        lucky_desc = new javax.swing.JTextArea();
        luckyb = new javax.swing.JButton();
        paul = new javax.swing.JDialog();
        paul_desc = new javax.swing.JTextArea();
        paulb = new javax.swing.JButton();
        pedro = new javax.swing.JDialog();
        pedro_desc = new javax.swing.JTextArea();
        pedrob = new javax.swing.JButton();
        rose = new javax.swing.JDialog();
        rose_desc = new javax.swing.JTextArea();
        roseb = new javax.swing.JButton();
        sid = new javax.swing.JDialog();
        sid_desc = new javax.swing.JTextArea();
        sidb = new javax.swing.JButton();
        slab = new javax.swing.JDialog();
        slab_desc = new javax.swing.JTextArea();
        slabb = new javax.swing.JButton();
        suzy = new javax.swing.JDialog();
        suzy_desc = new javax.swing.JTextArea();
        suzyb = new javax.swing.JButton();
        vulture = new javax.swing.JDialog();
        vulture_desc = new javax.swing.JTextArea();
        vultureb = new javax.swing.JButton();
        willy = new javax.swing.JDialog();
        willy_desc = new javax.swing.JTextArea();
        willyb = new javax.swing.JButton();


        char_select.setSize(new java.awt.Dimension(470, 550));
        char_select.setTitle("Character Special Abilities");
        bart.setTitle("Bart Cassidy");
        black.setTitle("Black Jack");
        gringo.setTitle("El Gringo");
        jesse.setTitle("Jesse Jones");
        jour.setTitle("Jourdonnais");
        kit.setTitle("Kit Carlson");
        lucky.setTitle("Lucky Duke");
        paul.setTitle("Paul Regret");
        pedro.setTitle("Pedro Ramirez");
        rose.setTitle("Rose Doolan");
        sid.setTitle("Sid Ketchum");
        slab.setTitle("Slab the Killer");
        suzy.setTitle("Suzy Lafayette");
        vulture.setTitle("Vulture Sam");
        willy.setTitle("Willy the Kid");
        

        bart_img.setToolTipText("");
        bart_img.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        bart_img.setSize(new java.awt.Dimension(100, 100));
        bart_img.setVerifyInputWhenFocusTarget(false);
        bart_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bart_imgMouseClicked(evt);
            }
        });

        black_img.setToolTipText("");
        black_img.setSize(new java.awt.Dimension(100, 100));
        black_img.setVerifyInputWhenFocusTarget(false);
        black_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                black_imgMouseClicked(evt);
            }
        });

        calamity_img.setToolTipText("");
        calamity_img.setSize(new java.awt.Dimension(100, 100));
        calamity_img.setVerifyInputWhenFocusTarget(false);
        calamity_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calamity_imgMouseClicked(evt);
            }
        });

        gringo_img.setToolTipText("");
        gringo_img.setSize(new java.awt.Dimension(100, 100));
        gringo_img.setVerifyInputWhenFocusTarget(false);
        gringo_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gringo_imgMouseClicked(evt);
            }
        });

        paul_img.setToolTipText("");
        paul_img.setSize(new java.awt.Dimension(100, 100));
        paul_img.setVerifyInputWhenFocusTarget(false);
        paul_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paul_imgMouseClicked(evt);
            }
        });

        pedro_img.setToolTipText("");
        pedro_img.setSize(new java.awt.Dimension(100, 100));
        pedro_img.setVerifyInputWhenFocusTarget(false);
        pedro_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedro_imgMouseClicked(evt);
            }
        });

        rose_img.setToolTipText("");
        rose_img.setSize(new java.awt.Dimension(100, 100));
        rose_img.setVerifyInputWhenFocusTarget(false);
        rose_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rose_imgMouseClicked(evt);
            }
        });

        sid_img.setToolTipText("");
        sid_img.setSize(new java.awt.Dimension(100, 100));
        sid_img.setVerifyInputWhenFocusTarget(false);
        sid_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sid_imgMouseClicked(evt);
            }
        });

        jesse_img.setToolTipText("");
        jesse_img.setSize(new java.awt.Dimension(100, 100));
        jesse_img.setVerifyInputWhenFocusTarget(false);
        jesse_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jesse_imgMouseClicked(evt);
            }
        });

        jour_img.setToolTipText("");
        jour_img.setSize(new java.awt.Dimension(100, 100));
        jour_img.setVerifyInputWhenFocusTarget(false);
        jour_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jour_imgMouseClicked(evt);
            }
        });

        kit_img.setToolTipText("");
        kit_img.setSize(new java.awt.Dimension(100, 100));
        kit_img.setVerifyInputWhenFocusTarget(false);
        kit_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kit_imgMouseClicked(evt);
            }
        });

        lucky_img.setToolTipText("");
        lucky_img.setSize(new java.awt.Dimension(100, 100));
        lucky_img.setVerifyInputWhenFocusTarget(false);
        lucky_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lucky_imgMouseClicked(evt);
            }
        });

        slab_img.setToolTipText("");
        slab_img.setSize(new java.awt.Dimension(100, 100));
        slab_img.setVerifyInputWhenFocusTarget(false);
        slab_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slab_imgMouseClicked(evt);
            }
        });

        suzy_img.setToolTipText("");
        suzy_img.setSize(new java.awt.Dimension(100, 100));
        suzy_img.setVerifyInputWhenFocusTarget(false);
        suzy_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suzy_imgMouseClicked(evt);
            }
        });

        vulture_img.setToolTipText("");
        vulture_img.setSize(new java.awt.Dimension(100, 100));
        vulture_img.setVerifyInputWhenFocusTarget(false);
        vulture_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vulture_imgMouseClicked(evt);
            }
        });

        willy_img.setToolTipText("");
        willy_img.setSize(new java.awt.Dimension(100, 100));
        willy_img.setVerifyInputWhenFocusTarget(false);
        willy_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                willy_imgMouseClicked(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Click on a character to view their special abilities.");

        javax.swing.GroupLayout char_selectLayout = new javax.swing.GroupLayout(char_select.getContentPane());
        char_select.getContentPane().setLayout(char_selectLayout);
        char_selectLayout.setHorizontalGroup(
            char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(char_selectLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jButton4))
            .addGroup(char_selectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(black_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bart_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gringo_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calamity_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lucky_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kit_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jour_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jesse_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paul_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedro_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rose_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sid_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vulture_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(willy_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slab_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suzy_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(char_selectLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel3))
        );

        char_selectLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bart_img, black_img, calamity_img, gringo_img, jesse_img, jour_img, kit_img, lucky_img, paul_img, pedro_img, rose_img, sid_img, slab_img, suzy_img, vulture_img, willy_img});

        char_selectLayout.setVerticalGroup(
            char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(char_selectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, char_selectLayout.createSequentialGroup()
                            .addComponent(jesse_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(jour_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(kit_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(lucky_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(char_selectLayout.createSequentialGroup()
                            .addComponent(bart_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(black_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(calamity_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(gringo_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(char_selectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(char_selectLayout.createSequentialGroup()
                            .addComponent(slab_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(suzy_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(vulture_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(willy_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(char_selectLayout.createSequentialGroup()
                            .addComponent(paul_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(pedro_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(rose_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(sid_img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        char_selectLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bart_img, black_img, calamity_img, gringo_img, jesse_img, jour_img, kit_img, lucky_img, paul_img, pedro_img, rose_img, sid_img, slab_img, suzy_img, vulture_img, willy_img});

        bart.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        bart.setPreferredSize(new java.awt.Dimension(367, 390));
        bart.setSize(new java.awt.Dimension(367, 390));

        bart_desc.setEditable(false);
        bart_desc.setColumns(20);
        bart_desc.setLineWrap(true);
        bart_desc.setRows(5);
        bart_desc.setText("Bart Cassidy\n(8 Life Points)\n\nYou may take an arrow instead of losing a life point (except to Indians or Dynamite).\nYou cannot use this ability if you lose a life point to Indian or Dynamite, only BULLSEYE1, BULLSEYE2, or Gatling Guns. You may not use this ability to take the last arrow remaining in the pile.");
        bart_desc.setWrapStyleWord(true);

        bartb.setText("Close");
        bartb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bartbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bartLayout = new javax.swing.GroupLayout(bart.getContentPane());
        bart.getContentPane().setLayout(bartLayout);
        bartLayout.setHorizontalGroup(
            bartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bart_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bartb))
                .addContainerGap())
        );
        bartLayout.setVerticalGroup(
            bartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bartLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bart_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bartb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        black.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        black.setPreferredSize(new java.awt.Dimension(367, 390));
        black.setSize(new java.awt.Dimension(367, 390));

        black_desc.setEditable(false);
        black_desc.setColumns(20);
        black_desc.setLineWrap(true);
        black_desc.setRows(5);
        black_desc.setText("Black Jack\n(8 Life Points)\n\nYou may re-roll Dynamite (not if you roll three or more!).\n\nIf you roll three or more Dynamite at once (or in total if you didn’t re-roll them), follow the usual rules (your turn ends, etc.).");
        black_desc.setWrapStyleWord(true);

        blackb.setText("Close");
        blackb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blackLayout = new javax.swing.GroupLayout(black.getContentPane());
        black.getContentPane().setLayout(blackLayout);
        blackLayout.setHorizontalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(black_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blackb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        blackLayout.setVerticalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(black_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blackb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        calamity.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        calamity.setPreferredSize(new java.awt.Dimension(367, 390));
        calamity.setSize(new java.awt.Dimension(367, 390));

        calamity_desc.setEditable(false);
        calamity_desc.setColumns(20);
        calamity_desc.setLineWrap(true);
        calamity_desc.setRows(5);
        calamity_desc.setText("Calamity Janet\n(8 Life Points)\n\nYou can use BULLSEYE1 as BULLSEYE2 and vice-versa.");
        calamity_desc.setWrapStyleWord(true);

        calamityb.setText("Close");
        calamityb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calamitybActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calamityLayout = new javax.swing.GroupLayout(calamity.getContentPane());
        calamity.getContentPane().setLayout(calamityLayout);
        calamityLayout.setHorizontalGroup(
            calamityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calamityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calamityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(calamity_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calamityb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calamityLayout.setVerticalGroup(
            calamityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calamityLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(calamity_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calamityb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        gringo.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        gringo.setPreferredSize(new java.awt.Dimension(367, 390));
        gringo.setSize(new java.awt.Dimension(367, 390));

        gringo_desc.setEditable(false);
        gringo_desc.setColumns(20);
        gringo_desc.setLineWrap(true);
        gringo_desc.setRows(5);
        gringo_desc.setText("El Gringo\n(7 Life Points)\n\nYou may re-roll Dynamite (not if you roll three or more!).\n\nIf you roll three or more Dynamite at once (or in total if you didn’t re-roll them), follow the usual rules (your turn ends, etc.).");
        gringo_desc.setWrapStyleWord(true);

        gringob.setText("Close");
        gringob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gringobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gringoLayout = new javax.swing.GroupLayout(gringo.getContentPane());
        gringo.getContentPane().setLayout(gringoLayout);
        gringoLayout.setHorizontalGroup(
            gringoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gringoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gringoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(gringo_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gringob))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gringoLayout.setVerticalGroup(
            gringoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gringoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(gringo_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gringob)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jesse.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jesse.setSize(new java.awt.Dimension(367, 390));

        jesse_desc.setEditable(false);
        jesse_desc.setColumns(20);
        jesse_desc.setLineWrap(true);
        jesse_desc.setRows(5);
        jesse_desc.setText("Jesse Jones\n(9 Life Points)\n\nIf you have four life points or less, you gain two if you use BEER for yourself.\nFor example, if you have four life points and use two beers, you get four life points.");
        jesse_desc.setWrapStyleWord(true);

        jesseb.setText("Close");
        jesseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jessebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jesseLayout = new javax.swing.GroupLayout(jesse.getContentPane());
        jesse.getContentPane().setLayout(jesseLayout);
        jesseLayout.setHorizontalGroup(
            jesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jesseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jesse_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jesseb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jesseLayout.setVerticalGroup(
            jesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jesseLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jesse_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jesseb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jour.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jour.setPreferredSize(new java.awt.Dimension(367, 390));
        jour.setSize(new java.awt.Dimension(367, 390));

        jour_desc.setEditable(false);
        jour_desc.setColumns(20);
        jour_desc.setLineWrap(true);
        jour_desc.setRows(5);
        jour_desc.setText("Jourdonnais\n(7 Life Points)\n\nYou never lose more than one life point to Indians.");
        jour_desc.setWrapStyleWord(true);

        jourb.setText("Close");
        jourb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jourbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jourLayout = new javax.swing.GroupLayout(jour.getContentPane());
        jour.getContentPane().setLayout(jourLayout);
        jourLayout.setHorizontalGroup(
            jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jour_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jourb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jourLayout.setVerticalGroup(
            jourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jourLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jour_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jourb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        kit.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        kit.setSize(new java.awt.Dimension(367, 390));

        kit_desc.setEditable(false);
        kit_desc.setColumns(20);
        kit_desc.setLineWrap(true);
        kit_desc.setRows(5);
        kit_desc.setText("Kit Carlson\n(7 Life Points)\n\nFor each GATLING you may discard one arrow from any player.\n\nYou may choose to discard your own arrows. If you roll three GATLING, you discard all your own arrows, plus three from any player(s) (of course, you still deal one damage to each other player).");
        kit_desc.setWrapStyleWord(true);

        kitb.setText("Close");
        kitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kitLayout = new javax.swing.GroupLayout(kit.getContentPane());
        kit.getContentPane().setLayout(kitLayout);
        kitLayout.setHorizontalGroup(
            kitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(kit_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kitb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kitLayout.setVerticalGroup(
            kitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(kit_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kitb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        lucky.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lucky.setSize(new java.awt.Dimension(367, 390));

        lucky_desc.setEditable(false);
        lucky_desc.setColumns(20);
        lucky_desc.setLineWrap(true);
        lucky_desc.setRows(5);
        lucky_desc.setText("Lucky Duke\n(8 Life Points)\n\nYou may make one extra re-roll.\n\n(You may roll the dice a total of four times on your turn.)");
        lucky_desc.setWrapStyleWord(true);

        luckyb.setText("Close");
        luckyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luckybActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout luckyLayout = new javax.swing.GroupLayout(lucky.getContentPane());
        lucky.getContentPane().setLayout(luckyLayout);
        luckyLayout.setHorizontalGroup(
            luckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luckyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(luckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lucky_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luckyb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        luckyLayout.setVerticalGroup(
            luckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luckyLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lucky_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(luckyb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        paul.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        paul.setSize(new java.awt.Dimension(367, 390));

        paul_desc.setEditable(false);
        paul_desc.setColumns(20);
        paul_desc.setLineWrap(true);
        paul_desc.setRows(5);
        paul_desc.setText("Paul Regret\n(9 Life Points)\n\nYou never lose life points to the Gatling Gun.");
        paul_desc.setWrapStyleWord(true);

        paulb.setText("Close");
        paulb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paulbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paulLayout = new javax.swing.GroupLayout(paul.getContentPane());
        paul.getContentPane().setLayout(paulLayout);
        paulLayout.setHorizontalGroup(
            paulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(paul_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paulb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paulLayout.setVerticalGroup(
            paulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paulLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(paul_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paulb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pedro.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pedro.setSize(new java.awt.Dimension(367, 390));

        pedro_desc.setEditable(false);
        pedro_desc.setColumns(20);
        pedro_desc.setLineWrap(true);
        pedro_desc.setRows(5);
        pedro_desc.setText("Pedro Ramirez\n(8 Life Points)\n\nEach time you lose a life point, you may discard one of your arrows.\n\nYou still lose the life point when you use this ability.");
        pedro_desc.setWrapStyleWord(true);

        pedrob.setText("Close");
        pedrob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedrobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pedroLayout = new javax.swing.GroupLayout(pedro.getContentPane());
        pedro.getContentPane().setLayout(pedroLayout);
        pedroLayout.setHorizontalGroup(
            pedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pedro_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedrob))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pedroLayout.setVerticalGroup(
            pedroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pedroLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(pedro_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pedrob)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        rose.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        rose.setSize(new java.awt.Dimension(367, 390));

        rose_desc.setEditable(false);
        rose_desc.setColumns(20);
        rose_desc.setLineWrap(true);
        rose_desc.setRows(5);
        rose_desc.setText("Rose Doolan\n(9 Life Points)\n\nYou may use BULLSEYE1 or BULLSEYE2 for players sitting one place further.\n\nWith BULLSEYE1 you may hit a player sitting up to two places away, and with BULLSEYE2 you may hit a player sitting two or three places away.");
        rose_desc.setWrapStyleWord(true);

        roseb.setText("Close");
        roseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roseLayout = new javax.swing.GroupLayout(rose.getContentPane());
        rose.getContentPane().setLayout(roseLayout);
        roseLayout.setHorizontalGroup(
            roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rose_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roseb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roseLayout.setVerticalGroup(
            roseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roseLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(rose_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roseb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        sid.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        sid.setSize(new java.awt.Dimension(367, 390));

        sid_desc.setEditable(false);
        sid_desc.setColumns(20);
        sid_desc.setLineWrap(true);
        sid_desc.setRows(5);
        sid_desc.setText("Sid Ketchum\n(8 Life Points)\n\nAt the beginning of your turn, any player of your choice gains one life point.\n\nYou may also choose yourself.");
        sid_desc.setWrapStyleWord(true);

        sidb.setText("Close");
        sidb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidLayout = new javax.swing.GroupLayout(sid.getContentPane());
        sid.getContentPane().setLayout(sidLayout);
        sidLayout.setHorizontalGroup(
            sidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(sid_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidLayout.setVerticalGroup(
            sidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(sid_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sidb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        slab.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        slab.setSize(new java.awt.Dimension(367, 390));

        slab_desc.setEditable(false);
        slab_desc.setColumns(20);
        slab_desc.setLineWrap(true);
        slab_desc.setRows(5);
        slab_desc.setText("Slab the Killer\n(8 Life Points)\n\nOnce per turn, you can use a BEER to double a BULLSEYE1 or BULLSEYE2.\n\nThe dice you double takes two life points away from the same player (you can’t choose two different players). The BEER in this case does not provide any life points.");
        slab_desc.setWrapStyleWord(true);

        slabb.setText("Close");
        slabb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slabbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout slabLayout = new javax.swing.GroupLayout(slab.getContentPane());
        slab.getContentPane().setLayout(slabLayout);
        slabLayout.setHorizontalGroup(
            slabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(slabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(slab_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slabb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        slabLayout.setVerticalGroup(
            slabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slabLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(slab_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slabb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        suzy.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        suzy.setSize(new java.awt.Dimension(367, 390));

        suzy_desc.setEditable(false);
        suzy_desc.setColumns(20);
        suzy_desc.setLineWrap(true);
        suzy_desc.setRows(5);
        suzy_desc.setText("Suzy Lafayette\n(8 Life Points)\n\nIf you didn’t roll any BULLSEYE1 or BULLSEYE2, you gain two life points.\n\nThis only applies at the END of your turn, not during your re-rolls.");
        suzy_desc.setWrapStyleWord(true);

        suzyb.setText("Close");
        suzyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suzybActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout suzyLayout = new javax.swing.GroupLayout(suzy.getContentPane());
        suzy.getContentPane().setLayout(suzyLayout);
        suzyLayout.setHorizontalGroup(
            suzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suzyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(suzy_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suzyb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        suzyLayout.setVerticalGroup(
            suzyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suzyLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(suzy_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suzyb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        vulture.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        vulture.setSize(new java.awt.Dimension(367, 390));

        vulture_desc.setEditable(false);
        vulture_desc.setColumns(20);
        vulture_desc.setLineWrap(true);
        vulture_desc.setRows(5);
        vulture_desc.setText("Vulture Sam\n(9 Life Points)\n\nEach time another player is eliminated, you gain two life points.");
        vulture_desc.setWrapStyleWord(true);

        vultureb.setText("Close");
        vultureb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vulturebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vultureLayout = new javax.swing.GroupLayout(vulture.getContentPane());
        vulture.getContentPane().setLayout(vultureLayout);
        vultureLayout.setHorizontalGroup(
            vultureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vultureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vultureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(vulture_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vultureb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vultureLayout.setVerticalGroup(
            vultureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vultureLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(vulture_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vultureb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        willy.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        willy.setSize(new java.awt.Dimension(367, 390));

        willy_desc.setEditable(false);
        willy_desc.setColumns(20);
        willy_desc.setLineWrap(true);
        willy_desc.setRows(5);
        willy_desc.setText("Willy the Kid\n(8 Life Points)\n\nYou only need 2 GATLING to use the Gatling Gun.\n\nYou can activate the Gatling Gun only once per turn, even if you roll more than two GATLING results.");
        willy_desc.setWrapStyleWord(true);

        willyb.setText("Close");
        willyb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                willybActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout willyLayout = new javax.swing.GroupLayout(willy.getContentPane());
        willy.getContentPane().setLayout(willyLayout);
        willyLayout.setHorizontalGroup(
            willyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(willyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(willyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(willy_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(willyb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        willyLayout.setVerticalGroup(
            willyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(willyLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(willy_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(willyb)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
                               

    public void scaleIcons(){
        Image img;
        
        ImageIcon bartp = new ImageIcon(getClass().getResource("/bang/media/bart.png"));
        img = bartp.getImage().getScaledInstance(bart_img.getWidth(), bart_img.getHeight(), Image.SCALE_SMOOTH);
        bart_img.setIcon(new ImageIcon(img));
        
        ImageIcon blackp = new ImageIcon(getClass().getResource("/bang/media/black.png"));
        img = blackp.getImage().getScaledInstance(black_img.getWidth(), black_img.getHeight(), Image.SCALE_SMOOTH);
        black_img.setIcon(new ImageIcon(img));
        
        ImageIcon calamityp = new ImageIcon(getClass().getResource("/bang/media/calamity.png"));
        img = calamityp.getImage().getScaledInstance(calamity_img.getWidth(), calamity_img.getHeight(), Image.SCALE_SMOOTH);
        calamity_img.setIcon(new ImageIcon(img));
        
        ImageIcon gringop = new ImageIcon(getClass().getResource("/bang/media/gringo.png"));
        img = gringop.getImage().getScaledInstance(gringo_img.getWidth(), gringo_img.getHeight(), Image.SCALE_SMOOTH);
        gringo_img.setIcon(new ImageIcon(img));
        
        ImageIcon jessep = new ImageIcon(getClass().getResource("/bang/media/jesse.png"));
        img = jessep.getImage().getScaledInstance(jesse_img.getWidth(), jesse_img.getHeight(), Image.SCALE_SMOOTH);
        jesse_img.setIcon(new ImageIcon(img));
        
        ImageIcon jourp = new ImageIcon(getClass().getResource("/bang/media/jour.png"));
        img = jourp.getImage().getScaledInstance(jour_img.getWidth(), jour_img.getHeight(), Image.SCALE_SMOOTH);
        jour_img.setIcon(new ImageIcon(img));
        
        ImageIcon kitp = new ImageIcon(getClass().getResource("/bang/media/kit.png"));
        img = kitp.getImage().getScaledInstance(kit_img.getWidth(), kit_img.getHeight(), Image.SCALE_SMOOTH);
        kit_img.setIcon(new ImageIcon(img));
        
        ImageIcon willyp = new ImageIcon(getClass().getResource("/bang/media/willy.png"));
        img = willyp.getImage().getScaledInstance(willy_img.getWidth(), willy_img.getHeight(), Image.SCALE_SMOOTH);
        willy_img.setIcon(new ImageIcon(img));
        
        ImageIcon vulturep = new ImageIcon(getClass().getResource("/bang/media/vulture.png"));
        img = vulturep.getImage().getScaledInstance(vulture_img.getWidth(), vulture_img.getHeight(), Image.SCALE_SMOOTH);
        vulture_img.setIcon(new ImageIcon(img));
        
        ImageIcon slabp = new ImageIcon(getClass().getResource("/bang/media/slab.png"));
        img = slabp.getImage().getScaledInstance(slab_img.getWidth(), slab_img.getHeight(), Image.SCALE_SMOOTH);
        slab_img.setIcon(new ImageIcon(img));
        
        ImageIcon sidp = new ImageIcon(getClass().getResource("/bang/media/sid.png"));
        img = sidp.getImage().getScaledInstance(sid_img.getWidth(), sid_img.getHeight(), Image.SCALE_SMOOTH);
        sid_img.setIcon(new ImageIcon(img));
        
        ImageIcon suzyp = new ImageIcon(getClass().getResource("/bang/media/suzy.png"));
        img = suzyp.getImage().getScaledInstance(suzy_img.getWidth(), suzy_img.getHeight(), Image.SCALE_SMOOTH);
        suzy_img.setIcon(new ImageIcon(img));
        
        ImageIcon rosep = new ImageIcon(getClass().getResource("/bang/media/rose.png"));
        img = rosep.getImage().getScaledInstance(rose_img.getWidth(), rose_img.getHeight(), Image.SCALE_SMOOTH);
        rose_img.setIcon(new ImageIcon(img));
        
        ImageIcon pedrop = new ImageIcon(getClass().getResource("/bang/media/pedro.png"));
        img = pedrop.getImage().getScaledInstance(pedro_img.getWidth(), pedro_img.getHeight(), Image.SCALE_SMOOTH);
        pedro_img.setIcon(new ImageIcon(img));
        
        ImageIcon paulp = new ImageIcon(getClass().getResource("/bang/media/paul.png"));
        img = paulp.getImage().getScaledInstance(paul_img.getWidth(), paul_img.getHeight(), Image.SCALE_SMOOTH);
        paul_img.setIcon(new ImageIcon(img));
        
        ImageIcon luckyp = new ImageIcon(getClass().getResource("/bang/media/lucky.png"));
        img = luckyp.getImage().getScaledInstance(lucky_img.getWidth(), lucky_img.getHeight(), Image.SCALE_SMOOTH);
        lucky_img.setIcon(new ImageIcon(img));
    }                                       

    private void bart_imgMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        bart.setLocationRelativeTo(null);
        bart.setVisible(true);
    }                                     

    private void bartbActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        bart.dispose();
    }                                     

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        char_select.dispose();
    }                                        

    private void blackbActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        black.dispose();
    }                                      

    private void calamitybActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        calamity.dispose();
    }                                         

    private void gringobActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        gringo.dispose();
    }                                       

    private void jessebActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        jesse.dispose();
    }                                      

    private void jourbActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        jour.dispose();
    }                                     

    private void kitbActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        kit.dispose();
    }                                    

    private void willybActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        willy.dispose();
    }                                      

    private void vulturebActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        vulture.dispose();
    }                                        

    private void suzybActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        suzy.dispose();
    }                                     

    private void slabbActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here
        slab.dispose();
    }                                     

    private void sidbActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        sid.dispose();
    }                                    

    private void rosebActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        rose.dispose();
    }                                     

    private void pedrobActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        pedro.dispose();
    }                                      

    private void paulbActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        paul.dispose();
    }                                     

    private void luckybActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        lucky.dispose();
    }                                      

    private void black_imgMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        black.setLocationRelativeTo(null);
        black.setVisible(true);
    }                                      

    private void calamity_imgMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        calamity.setLocationRelativeTo(null);
        calamity.setVisible(true);
    }                                         

    private void gringo_imgMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        gringo.setLocationRelativeTo(null);
        gringo.setVisible(true);
    }                                       

    private void paul_imgMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        paul.setLocationRelativeTo(null);
        paul.setVisible(true);
    }                                     

    private void pedro_imgMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        pedro.setLocationRelativeTo(null);
        pedro.setVisible(true);
    }                                      

    private void jesse_imgMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        jesse.setLocationRelativeTo(null);
        jesse.setVisible(true);
    }                                      

    private void jour_imgMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        jour.setLocationRelativeTo(null);
        jour.setVisible(true);
    }                                     

    private void kit_imgMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        kit.setLocationRelativeTo(null);
        kit.setVisible(true);
    }                                    

    private void lucky_imgMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        lucky.setLocationRelativeTo(null);
        lucky.setVisible(true);
    }                                      

    private void rose_imgMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        rose.setLocationRelativeTo(null);
        rose.setVisible(true);
    }                                     

    private void sid_imgMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        sid.setLocationRelativeTo(null);
        sid.setVisible(true);
    }                                    

    private void slab_imgMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        slab.setLocationRelativeTo(null);
        slab.setVisible(true);
    }                                     

    private void suzy_imgMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        suzy.setLocationRelativeTo(null);
        suzy.setVisible(true);
    }                                     

    private void vulture_imgMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        vulture.setLocationRelativeTo(null);
        vulture.setVisible(true);
    }                                        

    private void willy_imgMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        willy.setLocationRelativeTo(null);
        willy.setVisible(true);
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                                                           
    
    public void skip(){
        dispose();
        char_select.setLocationRelativeTo(null);
        char_select.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String [] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangSwingChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangSwingChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangSwingChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangSwingChar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangSwingChar().setVisible(false);
                
            }
        });

    }

    // Variables declaration - do not modify                     
    private javax.swing.JDialog bart;
    private javax.swing.JTextArea bart_desc;
    private javax.swing.JLabel bart_img;
    private javax.swing.JButton bartb;
    private javax.swing.JDialog black;
    private javax.swing.JTextArea black_desc;
    private javax.swing.JLabel black_img;
    private javax.swing.JButton blackb;
    private javax.swing.JDialog calamity;
    private javax.swing.JTextArea calamity_desc;
    private javax.swing.JLabel calamity_img;
    private javax.swing.JButton calamityb;
    private javax.swing.JDialog char_select;
    private javax.swing.JDialog gringo;
    private javax.swing.JTextArea gringo_desc;
    private javax.swing.JLabel gringo_img;
    private javax.swing.JButton gringob;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDialog jesse;
    private javax.swing.JTextArea jesse_desc;
    private javax.swing.JLabel jesse_img;
    private javax.swing.JButton jesseb;
    private javax.swing.JDialog jour;
    private javax.swing.JTextArea jour_desc;
    private javax.swing.JLabel jour_img;
    private javax.swing.JButton jourb;
    private javax.swing.JDialog kit;
    private javax.swing.JTextArea kit_desc;
    private javax.swing.JLabel kit_img;
    private javax.swing.JButton kitb;
    private javax.swing.JDialog lucky;
    private javax.swing.JTextArea lucky_desc;
    private javax.swing.JLabel lucky_img;
    private javax.swing.JButton luckyb;
    private javax.swing.JDialog paul;
    private javax.swing.JTextArea paul_desc;
    private javax.swing.JLabel paul_img;
    private javax.swing.JButton paulb;
    private javax.swing.JDialog pedro;
    private javax.swing.JTextArea pedro_desc;
    private javax.swing.JLabel pedro_img;
    private javax.swing.JButton pedrob;
    private javax.swing.JDialog rose;
    private javax.swing.JTextArea rose_desc;
    private javax.swing.JLabel rose_img;
    private javax.swing.JButton roseb;
    private javax.swing.JDialog sid;
    private javax.swing.JTextArea sid_desc;
    private javax.swing.JLabel sid_img;
    private javax.swing.JButton sidb;
    private javax.swing.JDialog slab;
    private javax.swing.JTextArea slab_desc;
    private javax.swing.JLabel slab_img;
    private javax.swing.JButton slabb;
    private javax.swing.JDialog suzy;
    private javax.swing.JTextArea suzy_desc;
    private javax.swing.JLabel suzy_img;
    private javax.swing.JButton suzyb;
    private javax.swing.JDialog vulture;
    private javax.swing.JTextArea vulture_desc;
    private javax.swing.JLabel vulture_img;
    private javax.swing.JButton vultureb;
    private javax.swing.JDialog willy;
    private javax.swing.JTextArea willy_desc;
    private javax.swing.JLabel willy_img;
    private javax.swing.JButton willyb;
    // End of variables declaration                   
}
