/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bang;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @MainAuthor Christiana Taylor 
 * @author Megan Lorfing
 * @author Seth Michaels
 * @author Sean Criswell
 * @author Hunter King
 */
public class BangSwingRules extends javax.swing.JFrame {
    
    int pageNum = 0;
    Image r0, r1, r2, r3;
    
    /**
     * Creates new form BangSwingRules
     */
    public BangSwingRules() {
        initComponents();
        scaleIcons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        spec_rules = new javax.swing.JDialog();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        spec_rulesb = new javax.swing.JButton();
        rules = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        spec_rules.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        spec_rules.setSize(new java.awt.Dimension(367, 390));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Shuffle these three roles: Deputy, Outlaw, and Renegade. Give one of them randomly to each player, but place them face up on the table. Everyone knows the role of all three players. \n\nThe goal of each player is determined by his role:\n• the Deputy must eliminate the Renegade; \n• the Renegade must eliminate the Outlaw; \n• the Outlaw must eliminate the Deputy.\n\nThe game plays as usual, with the Deputy taking the first turn. You win as soon as you reach your goal if you cause your target to lose his last life point (e.g., as the Deputy you must personally eliminate the Renegade). If the other player dealt the final hit, then the goal for both survivors is to be the last man standing. For example, if the Outlaw eliminated the Renegade, then the\nDeputy did not win—he must now eliminate the Outlaw, who must in turn eliminate the Deputy in order to win.");
        jTextArea3.setWrapStyleWord(true);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout spec_rulesLayout = new javax.swing.GroupLayout(spec_rules.getContentPane());
        spec_rules.getContentPane().setLayout(spec_rulesLayout);
        spec_rulesLayout.setHorizontalGroup(
            spec_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spec_rulesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spec_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap())
        );
        spec_rulesLayout.setVerticalGroup(
            spec_rulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spec_rulesLayout.createSequentialGroup()
                .addComponent(jTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Basic Rules");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        next.setText("Exit");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        spec_rulesb.setText("Special Rules");
        spec_rulesb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spec_rulesbActionPerformed(evt);
            }
        });

        rules.setText("rules");

        jButton1.setText("Prev");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spec_rulesb)
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(next)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rules, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spec_rulesb)
                    .addComponent(next)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:      
        dispose();
    }                                    

    public void scaleIcons(){
        
        ImageIcon rule0 = new ImageIcon(getClass().getResource("/bang/media/rule0.png"));
        r0 = rule0.getImage().getScaledInstance(rules.getWidth(), rules.getHeight(), Image.SCALE_SMOOTH);
        rules.setIcon(new ImageIcon(r0));
        
        ImageIcon rule1 = new ImageIcon(getClass().getResource("/bang/media/rule1.png"));
        r1 = rule1.getImage().getScaledInstance(rules.getWidth(), rules.getHeight(), Image.SCALE_SMOOTH);
        
        ImageIcon rule2 = new ImageIcon(getClass().getResource("/bang/media/rule2.png"));
        r2 = rule2.getImage().getScaledInstance(rules.getWidth(), rules.getHeight(), Image.SCALE_SMOOTH);
        
        ImageIcon rule3 = new ImageIcon(getClass().getResource("/bang/media/rule3.png"));
        r3 = rule3.getImage().getScaledInstance(rules.getWidth(), rules.getHeight(), Image.SCALE_SMOOTH);
        
    }
    
    private void spec_rulesbActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        spec_rules.setLocationRelativeTo(null);
        spec_rules.setVisible(true);
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        spec_rules.dispose();
    }                                                                           
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        pageNum--;
        
        switch(pageNum){
            case 0: rules.setIcon(new ImageIcon(r0));
                break;
            case 1: rules.setIcon(new ImageIcon(r1));
                break;
            case 2: rules.setIcon(new ImageIcon(r2));
                break;
            case 3: rules.setIcon(new ImageIcon(r3));
                break;

        }
    }                                     

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        pageNum++;
        
        switch(pageNum){
            case 0: rules.setIcon(new ImageIcon(r0));
                break;
            case 1: rules.setIcon(new ImageIcon(r1));
                break;
            case 2: rules.setIcon(new ImageIcon(r2));
                break;
            case 3: rules.setIcon(new ImageIcon(r3));
                break;

        }
    }                                     

    
    /**
     * @param args the command line arguments
     */
    public static void main(String [] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangSwingRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangSwingRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangSwingRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangSwingRules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangSwingRules().setVisible(true);
                
            }
        });

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton next;
    private javax.swing.JLabel rules;
    private javax.swing.JDialog spec_rules;
    private javax.swing.JButton spec_rulesb;
    // End of variables declaration                   
}

